// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSettingsByUserID = `-- name: GetSettingsByUserID :one
SELECT user_id, max_context_load_time, language
FROM user_settings
WHERE user_id = $1
`

func (q *Queries) GetSettingsByUserID(ctx context.Context, userID pgtype.UUID) (Settings, error) {
	row := q.db.QueryRow(ctx, getSettingsByUserID, userID)
	var i Settings
	err := row.Scan(
		&i.UserID,
		&i.MaxContextLoadTime,
		&i.Language,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO user_settings (user_id, max_context_load_time, language)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET
  max_context_load_time = EXCLUDED.max_context_load_time,
  language = EXCLUDED.language
RETURNING user_id, max_context_load_time, language
`

type UpsertSettingsParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	MaxContextLoadTime int32       `json:"max_context_load_time"`
	Language           string      `json:"language"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Settings, error) {
	row := q.db.QueryRow(ctx, upsertSettings, arg.UserID, arg.MaxContextLoadTime, arg.Language)
	var i Settings
	err := row.Scan(
		&i.UserID,
		&i.MaxContextLoadTime,
		&i.Language,
	)
	return i, err
}

const deleteSettingsByUserID = `-- name: DeleteSettingsByUserID :exec
DELETE FROM user_settings
WHERE user_id = $1
`

func (q *Queries) DeleteSettingsByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSettingsByUserID, userID)
	return err
}

